---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  ephemeral: "true"
  storage-class: default

namespace: storage-bench

bases:
- ../../bases/job
- ../../bases/namespace
