---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  ephemeral: "true"
  storage-class: gp3-csi

namespace: storage-bench

bases:
- ../../bases/job
- ../../bases/namespace

patches:
- path: patch.yaml
  target:
    kind: PersistentVolumeClaim
